#!/usr/bin/perl
use 5.014;
use warnings;
use strict;

my %total_bytes;
my $all = '**all**';

while(<>) {
	my ($source, $destination, $byte) = split;
	$total_bytes{$source}{$destination} += $byte;
	$total_bytes{$source}{$all} += $byte;
}

my @sources = sort {$total_bytes{$b}{$all} <=> $total_bytes{$a}{$all}} keys %total_bytes;

for my $source (@sources) {
	my @destination = sort {$total_bytes{$source}{$b} <=> $total_bytes{$source}{$a}} keys %{$total_bytes{$source}};
	for my $destination (@destination) {
		say  "$source => $destination: $total_bytes{$source}{$destination}  bytes";
	}
	say "";
}
