#!/usr/bin/perl
use warnings;
use strict;
use 5.014;

my @daniel = qw (hat shirt book);
my @yummy = qw (skirt pant vase);
my @cookie = qw(food bone meat);

my %all = (
	daniel => \@daniel,
	yummy => \@yummy,
	cookie => \@cookie,
);

check_items_for_all(\%all);

sub check_items_for_all {
	my $all_ref = shift;
	for my $person (keys %$all_ref) {
		check_required_items($person, $all_ref->{"$person"});
	}
}

sub check_required_items { 
	my $who = shift;
	my $items = shift;

	my %whose_items = map { $_, 1 } @$items;

	my @required = qw(preserver sunscreen water_bottle jacket);
	my @missing = ( );

	for my $item (@required) {
		unless ( $whose_items{$item} ) { # not found in list?
			print "$who is missing $item.\n";
			push @missing, $item; }
	}

	if (@missing) {
		print "Adding @missing to @$items for $who.\n"; 
		push @$items, @missing;
	} 
}
