#!/usr/bin/perl
use utf8;
use strict;
use warnings;

use v5.12;

my %patterns = (
  Gilligan   => qr/(?:Wiley )?Gilligan/,
  'Mary-Ann' => qr/Mary-Ann/,
  Ginger     => qr/Ginger/,
  Professor  => qr/(?:The )?Professor/,
  Skipper    => qr/Skipper/,
  'A Howell' => qr/Mrs?. Howell/,
);

my $position = rightmost( 
  'There is Mrs. Howell, Ginger, and Gilligan',
  \%patterns
);	

print "$position\n"; 
	
sub rightmost {
  my( $string, $patterns ) = @_;
  
  my $rightmost = -1;
  my @keys = keys $patterns;
  while( my( $i, $pattern ) = each @keys ) {
	my $position = $string =~ m/$pattern/ ? $-[0] : -1;
	$rightmost = $position if $position > $rightmost;
	}

return $rightmost; 		
}
